"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "es" | "en" | "nl";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isInitialized: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Traducciones
const translations = {
  es: {
    nav: {
      shop: "Tienda",
      events: "Eventos",
      about: "Sobre Nosotros",
      contact: "Contacto",
      cart: "Carrito",
      account: "Cuenta",
      home: "Inicio",
    },
    shop: {
      all_cocktails: "Todos los Cócteles",
      non_alcoholic: "Sin Alcohol",
      strong_drinks: "Bebidas Fuertes",
      light_fresh: "Ligero y Fresco",
      tropical: "Delicias Tropicales",
      from_price: "Desde €{price}",
      coming_soon: "Próximamente",
      add_to_cart: "Añadir al Carrito",
      view_details: "Ver Detalles",
      explore_now: "Explorar ahora",
    },
    sizes: {
      small_bottle: "Botella pequeña",
      shot: "Chupito",
      shots: "Chupitos",
    },
    favorites: {
      title: "Mis Favoritos",
      subtitle: "Tus cocktails espaciales favoritos guardados para siempre",
      empty: "No tienes favoritos aún",
      explore: "Explorar Catálogo",
      added_on: "Añadido el {date}",
    },
    settings: {
      title: "Configuración",
      subtitle:
        "Personaliza tu experiencia espacial y gestiona tus preferencias",
      appearance: "Apariencia",
      theme: "Tema",
      light: "Claro",
      dark: "Oscuro",
      coming_soon: "Próximamente",
      language: "Idioma y Región",
      language_label: "Idioma",
      currency: "Moneda",
      currency_note: "Solo EUR disponible para envíos en Holanda.",
      notifications: "Notificaciones",
      email_notifications: "Notificaciones por email",
      email_desc: "Recibe actualizaciones sobre tus pedidos",
      push_notifications: "Notificaciones push",
      push_desc: "Recibe notificaciones en tu navegador",
      marketing: "Marketing",
      marketing_desc: "Recibe ofertas y promociones especiales",
      privacy: "Privacidad",
      public_profile: "Perfil público",
      public_profile_desc: "Permite que otros usuarios vean tu perfil",
      show_orders: "Mostrar pedidos",
      show_orders_desc: "Permite que otros vean tus pedidos públicos",
      save_changes: "Guardar Cambios",
      unsaved_changes: "Tienes cambios sin guardar",
      saved: "Configuración guardada!",
      error: "Error: {error}",
    },
    footer: {
      explore: "Explorar",
      description:
        "Bebidas curadas y experiencias premium de cócteles, servidas con sabor estelar.",
      contact: "Contacto:",
      copyright: "© 2025 CosmoCocktails. Todos los derechos reservados.",
    },
    admin: {
      panel_title: "Panel de Administración",
      panel_description: "Acceso exclusivo para administradores",
      access_button: "Acceder al Panel",
      redirecting: "Redirigiendo...",
      access_granted: "Acceso concedido al panel de administración",
      access_denied: "Acceso denegado. Permisos insuficientes.",
      session_expired: "Sesión expirada. Por favor, inicia sesión nuevamente.",
      popup_blocked:
        "Popup bloqueado. Permite ventanas emergentes para continuar.",
      access_error: "Error al acceder al panel de administración",
      security_notice: "Acceso restringido solo a personal autorizado",
    },
    common: {
      loading: "Cargando...",
      error: "Error",
      error_loading_sizes: "Error al cargar tamaños",
      unknown_error: "Error desconocido",
      retry: "Reintentar",
      save: "Guardar",
      cancel: "Cancelar",
      close: "Cerrar",
      back: "Volver",
      reload: "Recargar",
    },
    home: {
      hero_title: "Cócteles de calidad entregados en tu órbita",
      hero_subtitle: "",
      hero_description: "Creados por mixólogos. Servidos con sabor estelar.",
      explore_button: "Explorar Ahora",
      how_it_works: "Cómo Funciona",
      step1_title: "Elige tu cóctel",
      step1_description:
        "Navega por nuestra selección curada de cócteles premium",
      step2_title: "Personaliza tu pedido",
      step2_description:
        "Selecciona el tamaño y personaliza según tus preferencias",
      step3_title: "Recibe en casa",
      step3_description:
        "Disfruta de cócteles de calidad de bar en la comodidad de tu hogar",
      featured_title: "Cócteles Destacados",
      featured_subtitle: "Nuestra selección más popular",
      cta_title: "¿Listo para tu viaje espacial?",
      cta_description: "Descubre el universo de sabores que te espera",
      cta_button: "Comenzar Ahora",
    },
    about: {
      title: "¿Qué es CosmoCocktails?",
      description:
        "CosmoCocktails nace de nuestra pasión por la mixología. Creamos cócteles de calidad de bar con ingredientes premium para que puedas disfrutarlos en cualquier lugar. Listos para servir, hermosamente empaquetados y siempre deliciosos.",
      how_help_title: "¿Cómo podemos ayudarte?",
      help1: "Cócteles premium entregados a tu puerta",
      help2: "Listos para beber — no necesitas habilidades de mixología",
      help3: "Recetas curadas para cada paladar",
      help4: "Perfectos para fiestas o relajarse en casa",
      mission_title: "Nuestra Misión",
      mission_description:
        "Llevar la experiencia de bar premium directamente a tu hogar, con cócteles que rivalizan con los mejores establecimientos del mundo.",
      values_title: "Nuestros Valores",
      quality: "Calidad",
      quality_desc: "Solo los mejores ingredientes y técnicas de mixología",
      innovation: "Innovación",
      innovation_desc: "Recetas únicas y presentaciones creativas",
      sustainability: "Sostenibilidad",
      sustainability_desc: "Embalaje ecológico y prácticas responsables",
    },
    contact: {
      title: "Contacto",
      subtitle: "¿Tienes alguna pregunta? Estamos aquí para ayudarte",
      form_name: "Nombre",
      form_email: "Email",
      form_subject: "Asunto",
      form_message: "Mensaje",
      form_send: "Enviar Mensaje",
      form_sending: "Enviando...",
      form_success: "¡Mensaje enviado correctamente!",
      form_error: "Error al enviar el mensaje",
      info_title: "Información de Contacto",
      email: "Email",
      phone: "Teléfono",
      address: "Dirección",
      hours: "Horarios",
      hours_weekdays: "Lunes - Viernes: 9:00 - 18:00",
      hours_weekend: "Sábados: 10:00 - 16:00",
      social_title: "Síguenos",
    },
    events: {
      title: "Eventos",
      subtitle: "Únete a nuestras experiencias cósmicas",
      upcoming_title: "Próximos Eventos",
      past_title: "Eventos Anteriores",
      no_events: "No hay eventos programados",
      event_register: "Registrarse",
      event_details: "Ver Detalles",
      event_date: "Fecha",
      event_time: "Hora",
      event_location: "Ubicación",
      event_price: "Precio",
      event_description: "Descripción",
      card1_title: "Fiesta de Lanzamiento CosmoCocktails",
      card1_description:
        "Nuestro debut oficial en Róterdam con bebidas de autor y DJ en vivo.",
      card2_title: "Taller de Mixología Estelar",
      card2_description:
        "Masterclass práctica explorando los secretos de nuestras mezclas más populares.",
      card3_title: "Fiesta Galáctica de Año Nuevo",
      card3_description:
        "Despide el año entre las estrellas con cócteles cósmicos y sorpresas.",
    },
    cart: {
      title: "Carrito",
      item: "artículo",
      items: "artículos",
      in_cart: "en tu carrito",
      empty_title: "Tu carrito está vacío",
      empty_description:
        "Explora nuestros cócteles y añade algunos a tu carrito",
      empty_button: "Explorar Cócteles",
      item_name: "Cóctel",
      item_size: "Tamaño",
      item_quantity: "Cantidad",
      item_price: "Precio",
      item_total: "Total",
      remove_item: "Eliminar del carrito",
      update_quantity: "Actualizar",
      subtotal: "Subtotal",
      shipping: "Envío",
      free: "Gratis",
      tax: "Impuestos",
      total: "Total",
      checkout_button: "Proceder al Pago",
      continue_shopping: "Continuar Comprando",
      order_summary: "Resumen del Pedido",
      clear_cart: "Vaciar Carrito",
      free_shipping_note: "Envío gratis en pedidos superiores a 50€",
      decrease_qty: "Disminuir cantidad",
      increase_qty: "Aumentar cantidad",
    },
    checkout: {
      title: "Finalizar Compra",
      billing_title: "Información de Facturación",
      shipping_title: "Información de Envío",
      payment_title: "Información de Pago",
      order_summary: "Resumen del Pedido",
      first_name: "Nombre",
      last_name: "Apellido",
      email: "Email",
      phone: "Teléfono",
      address: "Dirección",
      city: "Ciudad",
      postal_code: "Código Postal",
      country: "País",
      card_number: "Número de Tarjeta",
      expiry_date: "Fecha de Vencimiento",
      cvv: "CVV",
      place_order: "Realizar Pedido",
      processing: "Procesando...",
      success_title: "¡Pedido Realizado!",
      success_message: "Tu pedido ha sido procesado correctamente",
      order_number: "Número de Pedido",
      estimated_delivery: "Entrega Estimada",
    },
    cocktail: {
      back_to_shop: "Volver a la Tienda",
      add_to_cart: "Añadir al Carrito",
      ingredients: "Ingredientes",
      instructions: "Instrucciones",
      nutrition: "Información Nutricional",
      alcohol_content: "Contenido de Alcohol",
      alcohol_strength: "Intensidad de alcohol",
      volume: "Volumen",
      calories: "Calorías",
      sugar: "Azúcar",
      related_cocktails: "Cócteles Relacionados",
      size_selection: "Seleccionar Tamaño",
      available_sizes: "Tamaños Disponibles",
      flavor_profile: "Perfil de sabor",
      non_alcoholic_available: "Opción sin alcohol disponible",
      non_alcoholic: "Sin alcohol",
      alcohol: "alcohol",
      non_alcoholic_version_available: "Versión sin alcohol disponible",
      quantity: "Cantidad",
      total_price: "Precio Total",
      no_sizes: "No hay tamaños disponibles.",
    },
    account: {
      my_account: "Mi Cuenta",
      logout: "Cerrar Sesión",
      customer_role: "Cliente",
      not_specified: "No especificado",
      default_user: "Usuario",
      error_updating_profile: "Error al actualizar perfil",
      tabs: {
        dashboard: "Panel",
        profile: "Perfil",
        orders: "Pedidos",
        favorites: "Favoritos",
        settings: "Configuración",
      },
    },
    orders: {
      title: "Mis Pedidos",
      subtitle: "Gestiona y revisa todos tus pedidos espaciales",
      empty_title: "Aún no tienes pedidos",
      empty_subtitle:
        "¡Explora nuestro catálogo de cocktails espaciales y haz tu primer pedido!",
      view_details: "Ver Detalles",
      retry: "Reintentar",
      order_details: "Detalles del Pedido",
      order_total: "Total del Pedido:",
      items_total: "en total",
      status: {
        completed: "Completado",
        pending: "Pendiente",
        cancelled: "Cancelado",
        shipped: "Enviado",
      },
    },
    profile: {
      header_edit: "Editar",
      header_cancel: "Cancelar",
      personal_info: "Información Personal",
      full_name: "Nombre Completo",
      email_note: "El email no se puede cambiar por seguridad",
      phone: "Teléfono",
      account_info: "Información de la Cuenta",
      member_since: "Miembro desde",
      last_update: "Última actualización",
      unspecified: "No especificado",
      cancel: "Cancelar",
      save_changes: "Guardar Cambios",
      saving: "Guardando...",
    },
  },
  en: {
    nav: {
      shop: "Shop",
      events: "Events",
      about: "About Us",
      contact: "Contact",
      cart: "Cart",
      account: "Account",
      home: "Home",
    },
    shop: {
      all_cocktails: "All Cocktails",
      non_alcoholic: "Non-Alcoholic",
      strong_drinks: "Strong Drinks",
      light_fresh: "Light & Fresh",
      tropical: "Tropical Delights",
      from_price: "From €{price}",
      coming_soon: "Coming Soon",
      add_to_cart: "Add to Cart",
      view_details: "View Details",
      explore_now: "Explore now",
    },
    sizes: {
      small_bottle: "Small bottle",
      shot: "Shot",
      shots: "Shots",
    },
    favorites: {
      title: "My Favorites",
      subtitle: "Your favorite space cocktails saved forever",
      empty: "You don't have favorites yet",
      explore: "Explore Catalog",
      added_on: "Added on {date}",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize your space experience and manage your preferences",
      appearance: "Appearance",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      coming_soon: "Coming Soon",
      language: "Language & Region",
      language_label: "Language",
      currency: "Currency",
      currency_note: "Only EUR available for shipping to Netherlands.",
      notifications: "Notifications",
      email_notifications: "Email notifications",
      email_desc: "Receive updates about your orders",
      push_notifications: "Push notifications",
      push_desc: "Receive notifications in your browser",
      marketing: "Marketing",
      marketing_desc: "Receive special offers and promotions",
      privacy: "Privacy",
      public_profile: "Public profile",
      public_profile_desc: "Allow other users to see your profile",
      show_orders: "Show orders",
      show_orders_desc: "Allow others to see your public orders",
      save_changes: "Save Changes",
      unsaved_changes: "You have unsaved changes",
      saved: "Settings saved!",
      error: "Error: {error}",
    },
    footer: {
      explore: "Explore",
      description:
        "Curated drinks & premium cocktail experiences, served with stellar taste.",
      contact: "Contact:",
      copyright: "© 2025 CosmoCocktails. All rights reserved.",
    },
    admin: {
      panel_title: "Administration Panel",
      panel_description: "Exclusive access for administrators",
      access_button: "Access Panel",
      redirecting: "Redirecting...",
      access_granted: "Access granted to administration panel",
      access_denied: "Access denied. Insufficient permissions.",
      session_expired: "Session expired. Please log in again.",
      popup_blocked: "Popup blocked. Allow popups to continue.",
      access_error: "Error accessing administration panel",
      security_notice: "Access restricted to authorized personnel only",
    },
    common: {
      loading: "Loading...",
      error: "Error",
      error_loading_sizes: "Error loading sizes",
      unknown_error: "Unknown error",
      retry: "Retry",
      save: "Save",
      cancel: "Cancel",
      close: "Close",
      back: "Back",
      reload: "Reload",
    },
    home: {
      hero_title: "Bar-quality cocktails.",
      hero_subtitle: "Delivered to your orbit.",
      hero_description: "Crafted by mixologists. Served with stellar taste.",
      explore_button: "Explore Now",
      how_it_works: "How It Works",
      step1_title: "Choose your cocktail",
      step1_description: "Browse our curated selection of premium cocktails",
      step2_title: "Customize your order",
      step2_description:
        "Select size and customize according to your preferences",
      step3_title: "Receive at home",
      step3_description:
        "Enjoy bar-quality cocktails in the comfort of your home",
      featured_title: "Featured Cocktails",
      featured_subtitle: "Our most popular selection",
      cta_title: "Ready for your space journey?",
      cta_description: "Discover the universe of flavors waiting for you",
      cta_button: "Start Now",
    },
    about: {
      title: "What is CosmoCocktails?",
      description:
        "CosmoCocktails is born from our passion for mixology. We craft bar-quality cocktails with premium ingredients so you can enjoy them anywhere. Ready to serve, beautifully packaged and always delicious.",
      how_help_title: "How can we help you?",
      help1: "Premium cocktails delivered to your door",
      help2: "Ready to drink — no mixology skills needed",
      help3: "Curated recipes for every taste",
      help4: "Perfect for parties or relaxing at home",
      mission_title: "Our Mission",
      mission_description:
        "Bring the premium bar experience directly to your home, with cocktails that rival the world's best establishments.",
      values_title: "Our Values",
      quality: "Quality",
      quality_desc: "Only the best ingredients and mixology techniques",
      innovation: "Innovation",
      innovation_desc: "Unique recipes and creative presentations",
      sustainability: "Sustainability",
      sustainability_desc: "Eco-friendly packaging and responsible practices",
    },
    contact: {
      title: "Contact",
      subtitle: "Have any questions? We're here to help",
      form_name: "Name",
      form_email: "Email",
      form_subject: "Subject",
      form_message: "Message",
      form_send: "Send Message",
      form_sending: "Sending...",
      form_success: "Message sent successfully!",
      form_error: "Error sending message",
      info_title: "Contact Information",
      email: "Email",
      phone: "Phone",
      address: "Address",
      hours: "Hours",
      hours_weekdays: "Monday - Friday: 9:00 - 18:00",
      hours_weekend: "Saturdays: 10:00 - 16:00",
      social_title: "Follow Us",
    },
    events: {
      title: "Events",
      subtitle: "Join our cosmic experiences",
      upcoming_title: "Upcoming Events",
      past_title: "Past Events",
      no_events: "No events scheduled",
      event_register: "Register",
      event_details: "View Details",
      event_date: "Date",
      event_time: "Time",
      event_location: "Location",
      event_price: "Price",
      event_description: "Description",
      card1_title: "CosmoCocktails Launch Party",
      card1_description:
        "Our official debut in Rotterdam with signature drinks and live DJ.",
      card2_title: "Stellar Mixology Workshop",
      card2_description:
        "Hands-on masterclass exploring the secrets behind our most popular blends.",
      card3_title: "Galactic New Year's Bash",
      card3_description:
        "Ring in the new year among the stars with cosmic cocktails and surprises.",
    },
    cart: {
      title: "Cart",
      empty_title: "Your cart is empty",
      empty_description: "Explore our cocktails and add some to your cart",
      empty_button: "Explore Cocktails",
      item_name: "Cocktail",
      item_size: "Size",
      item_quantity: "Quantity",
      item_price: "Price",
      item_total: "Total",
      remove_item: "Remove",
      update_quantity: "Update",
      subtotal: "Subtotal",
      shipping: "Shipping",
      tax: "Tax",
      total: "Total",
      checkout_button: "Proceed to Checkout",
      continue_shopping: "Continue Shopping",
    },
    checkout: {
      title: "Checkout",
      billing_title: "Billing Information",
      shipping_title: "Shipping Information",
      payment_title: "Payment Information",
      order_summary: "Order Summary",
      first_name: "First Name",
      last_name: "Last Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      city: "City",
      postal_code: "Postal Code",
      country: "Country",
      card_number: "Card Number",
      expiry_date: "Expiry Date",
      cvv: "CVV",
      place_order: "Place Order",
      processing: "Processing...",
      success_title: "Order Placed!",
      success_message: "Your order has been processed successfully",
      order_number: "Order Number",
      estimated_delivery: "Estimated Delivery",
    },
    cocktail: {
      back_to_shop: "Back to Shop",
      add_to_cart: "Add to Cart",
      ingredients: "Ingredients",
      instructions: "Instructions",
      nutrition: "Nutrition Information",
      alcohol_content: "Alcohol Content",
      alcohol_strength: "Alcohol strength",
      volume: "Volume",
      calories: "Calories",
      sugar: "Sugar",
      related_cocktails: "Related Cocktails",
      size_selection: "Select Size",
      available_sizes: "Available Sizes",
      flavor_profile: "Flavor profile",
      non_alcoholic_available: "Non-alcoholic option available",
      non_alcoholic: "Non-alcoholic",
      alcohol: "alcohol",
      non_alcoholic_version_available: "Non-alcoholic version available",
      quantity: "Quantity",
      total_price: "Total Price",
      no_sizes: "No sizes available.",
    },
    account: {
      my_account: "My Account",
      logout: "Log Out",
      customer_role: "Customer",
      not_specified: "Not specified",
      default_user: "User",
      error_updating_profile: "Error updating profile",
      tabs: {
        dashboard: "Dashboard",
        profile: "Profile",
        orders: "Orders",
        favorites: "Favorites",
        settings: "Settings",
      },
    },
    orders: {
      title: "My Orders",
      subtitle: "Manage and review all your cosmic orders",
      empty_title: "You don't have orders yet",
      empty_subtitle:
        "Explore our cosmic cocktail catalog and place your first order!",
      view_details: "View Details",
      retry: "Retry",
      order_details: "Order Details",
      order_total: "Order Total:",
      items_total: "in total",
      status: {
        completed: "Completed",
        pending: "Pending",
        cancelled: "Cancelled",
        shipped: "Shipped",
      },
    },
    profile: {
      header_edit: "Edit",
      header_cancel: "Cancel",
      personal_info: "Personal Information",
      full_name: "Full Name",
      email_note: "Email cannot be changed for security",
      phone: "Phone",
      account_info: "Account Information",
      member_since: "Member since",
      last_update: "Last update",
      unspecified: "Unspecified",
      cancel: "Cancel",
      save_changes: "Save Changes",
      saving: "Saving...",
    },
  },
  nl: {
    nav: {
      shop: "Winkel",
      events: "Evenementen",
      about: "Over Ons",
      contact: "Contact",
      cart: "Winkelwagen",
      account: "Account",
      home: "Home",
    },
    shop: {
      all_cocktails: "Alle Cocktails",
      non_alcoholic: "Alcoholvrij",
      strong_drinks: "Sterke Drankjes",
      light_fresh: "Licht & Vers",
      tropical: "Tropische Delicatessen",
      from_price: "Vanaf €{price}",
      coming_soon: "Binnenkort",
      add_to_cart: "Toevoegen aan Winkelwagen",
      view_details: "Bekijk Details",
      explore_now: "Nu verkennen",
    },
    sizes: {
      small_bottle: "Kleine fles",
      shot: "Shot",
      shots: "Shots",
    },
    favorites: {
      title: "Mijn Favorieten",
      subtitle: "Je favoriete ruimte cocktails voor altijd bewaard",
      empty: "Je hebt nog geen favorieten",
      explore: "Verken Catalogus",
      added_on: "Toegevoegd op {date}",
    },
    settings: {
      title: "Instellingen",
      subtitle: "Pas je ruimte-ervaring aan en beheer je voorkeuren",
      appearance: "Uiterlijk",
      theme: "Thema",
      light: "Licht",
      dark: "Donker",
      coming_soon: "Binnenkort",
      language: "Taal & Regio",
      language_label: "Taal",
      currency: "Valuta",
      currency_note: "Alleen EUR beschikbaar voor verzending naar Nederland.",
      notifications: "Meldingen",
      email_notifications: "E-mail meldingen",
      email_desc: "Ontvang updates over je bestellingen",
      push_notifications: "Push meldingen",
      push_desc: "Ontvang meldingen in je browser",
      marketing: "Marketing",
      marketing_desc: "Ontvang speciale aanbiedingen en promoties",
      privacy: "Privacy",
      public_profile: "Openbaar profiel",
      public_profile_desc: "Sta andere gebruikers toe je profiel te bekijken",
      show_orders: "Toon bestellingen",
      show_orders_desc: "Sta anderen toe je openbare bestellingen te bekijken",
      save_changes: "Wijzigingen Opslaan",
      unsaved_changes: "Je hebt niet-opgeslagen wijzigingen",
      saved: "Instellingen opgeslagen!",
      error: "Fout: {error}",
    },
    footer: {
      explore: "Verken",
      description:
        "Gecureerde drankjes & premium cocktail ervaringen, geserveerd met sterren smaak.",
      contact: "Contact:",
      copyright: "© 2025 CosmoCocktails. Alle rechten voorbehouden.",
    },
    orders: {
      title: "Mijn Bestellingen",
      subtitle: "Beheer en bekijk al je kosmische bestellingen",
      empty_title: "Je hebt nog geen bestellingen",
      empty_subtitle:
        "Verken onze kosmische cocktailcatalogus en plaats je eerste bestelling!",
      view_details: "Bekijk Details",
      retry: "Opnieuw proberen",
      order_details: "Bestelling Details",
      order_total: "Totaal Bestelling:",
      items_total: "in totaal",
      status: {
        completed: "Voltooid",
        pending: "In behandeling",
        cancelled: "Geannuleerd",
        shipped: "Verzonden",
      },
    },
    profile: {
      header_edit: "Bewerken",
      header_cancel: "Annuleren",
      personal_info: "Persoonlijke Informatie",
      full_name: "Volledige Naam",
      email_note: "E-mail kan om veiligheidsredenen niet worden gewijzigd",
      phone: "Telefoon",
      account_info: "Accountinformatie",
      member_since: "Lid sinds",
      last_update: "Laatste update",
      unspecified: "Niet gespecificeerd",
      cancel: "Annuleren",
      save_changes: "Wijzigingen Opslaan",
      saving: "Opslaan...",
    },
    account: {
      my_account: "Mijn Account",
      logout: "Uitloggen",
      customer_role: "Klant",
      not_specified: "Niet gespecificeerd",
      default_user: "Gebruiker",
      error_updating_profile: "Fout bij bijwerken van profiel",
      tabs: {
        dashboard: "Dashboard",
        profile: "Profiel",
        orders: "Bestellingen",
        favorites: "Favorieten",
        settings: "Instellingen",
      },
    },
    admin: {
      panel_title: "Beheerpaneel",
      panel_description: "Exclusieve toegang voor beheerders",
      access_button: "Toegang tot Paneel",
      redirecting: "Doorverwijzen...",
      access_granted: "Toegang verleend tot beheerpaneel",
      access_denied: "Toegang geweigerd. Onvoldoende rechten.",
      session_expired: "Sessie verlopen. Log opnieuw in.",
      popup_blocked: "Popup geblokkeerd. Sta popups toe om door te gaan.",
      access_error: "Fout bij toegang tot beheerpaneel",
      security_notice: "Toegang beperkt tot geautoriseerd personeel",
    },
    common: {
      loading: "Laden...",
      error: "Fout",
      error_loading_sizes: "Fout bij laden van maten",
      unknown_error: "Onbekende fout",
      retry: "Opnieuw proberen",
      save: "Opslaan",
      cancel: "Annuleren",
      close: "Sluiten",
      back: "Terug",
      reload: "Herladen",
    },
    home: {
      hero_title: "Bar-kwaliteit cocktails.",
      hero_subtitle: "Bezorgd op jouw baan.",
      hero_description: "Gemaakt door mixologen. Geserveerd met sterren smaak.",
      explore_button: "Verken Nu",
      how_it_works: "Hoe Het Werkt",
      step1_title: "Kies je cocktail",
      step1_description:
        "Blader door onze gecureerde selectie van premium cocktails",
      step2_title: "Personaliseer je bestelling",
      step2_description:
        "Selecteer maat en personaliseer volgens je voorkeuren",
      step3_title: "Ontvang thuis",
      step3_description:
        "Geniet van bar-kwaliteit cocktails in het comfort van je huis",
      featured_title: "Uitgelichte Cocktails",
      featured_subtitle: "Onze meest populaire selectie",
      cta_title: "Klaar voor je ruimtereis?",
      cta_description: "Ontdek het universum van smaken dat op je wacht",
      cta_button: "Begin Nu",
    },
    about: {
      title: "Wat is CosmoCocktails?",
      description:
        "CosmoCocktails is geboren uit onze passie voor mixologie. We maken bar-kwaliteit cocktails met premium ingrediënten zodat je ze overal kunt genieten. Klaar om te serveren, prachtig verpakt en altijd heerlijk.",
      how_help_title: "Hoe kunnen we je helpen?",
      help1: "Premium cocktails bezorgd aan je deur",
      help2: "Klaar om te drinken — geen mixologie vaardigheden nodig",
      help3: "Gecureerde recepten voor elke smaak",
      help4: "Perfect voor feesten of thuis ontspannen",
      mission_title: "Onze Missie",
      mission_description:
        "Breng de premium bar-ervaring direct naar je huis, met cocktails die wedijveren met de beste etablissementen ter wereld.",
      values_title: "Onze Waarden",
      quality: "Kwaliteit",
      quality_desc: "Alleen de beste ingrediënten en mixologie technieken",
      innovation: "Innovatie",
      innovation_desc: "Unieke recepten en creatieve presentaties",
      sustainability: "Duurzaamheid",
      sustainability_desc:
        "Milieuvriendelijke verpakking en verantwoorde praktijken",
    },
    contact: {
      title: "Contact",
      subtitle: "Heb je vragen? We zijn er om je te helpen",
      form_name: "Naam",
      form_email: "Email",
      form_subject: "Onderwerp",
      form_message: "Bericht",
      form_send: "Verstuur Bericht",
      form_sending: "Verzenden...",
      form_success: "Bericht succesvol verzonden!",
      form_error: "Fout bij verzenden bericht",
      info_title: "Contact Informatie",
      email: "Email",
      phone: "Telefoon",
      address: "Adres",
      hours: "Openingstijden",
      hours_weekdays: "Maandag - Vrijdag: 9:00 - 18:00",
      hours_weekend: "Zaterdagen: 10:00 - 16:00",
      social_title: "Volg Ons",
    },
    events: {
      title: "Evenementen",
      subtitle: "Doe mee aan onze kosmische ervaringen",
      upcoming_title: "Aankomende Evenementen",
      past_title: "Vorige Evenementen",
      no_events: "Geen evenementen gepland",
      event_register: "Registreren",
      event_details: "Bekijk Details",
      event_date: "Datum",
      event_time: "Tijd",
      event_location: "Locatie",
      event_price: "Prijs",
      event_description: "Beschrijving",
      card1_title: "CosmoCocktails Lancering",
      card1_description:
        "Onze officiële debuut in Rotterdam met signature drankjes en live DJ.",
      card2_title: "Stellaire Mixologie Workshop",
      card2_description:
        "Hands-on masterclass met de geheimen achter onze populairste blends.",
      card3_title: "Galactisch Oud & Nieuw Feest",
      card3_description:
        "Vier het nieuwe jaar tussen de sterren met kosmische cocktails en verrassingen.",
    },
    cart: {
      title: "Winkelwagen",
      empty_title: "Je winkelwagen is leeg",
      empty_description:
        "Verken onze cocktails en voeg er wat toe aan je winkelwagen",
      empty_button: "Verken Cocktails",
      item_name: "Cocktail",
      item_size: "Maat",
      item_quantity: "Hoeveelheid",
      item_price: "Prijs",
      item_total: "Totaal",
      remove_item: "Verwijderen",
      update_quantity: "Bijwerken",
      subtotal: "Subtotaal",
      shipping: "Verzending",
      tax: "Belasting",
      total: "Totaal",
      checkout_button: "Doorgaan naar Kassa",
      continue_shopping: "Verder Winkelen",
    },
    checkout: {
      title: "Afrekenen",
      billing_title: "Factuur Informatie",
      shipping_title: "Verzend Informatie",
      payment_title: "Betalings Informatie",
      order_summary: "Bestelling Overzicht",
      first_name: "Voornaam",
      last_name: "Achternaam",
      email: "Email",
      phone: "Telefoon",
      address: "Adres",
      city: "Stad",
      postal_code: "Postcode",
      country: "Land",
      card_number: "Kaartnummer",
      expiry_date: "Vervaldatum",
      cvv: "CVV",
      place_order: "Bestelling Plaatsen",
      processing: "Verwerken...",
      success_title: "Bestelling Geplaatst!",
      success_message: "Je bestelling is succesvol verwerkt",
      order_number: "Bestelnummer",
      estimated_delivery: "Geschatte Levering",
    },
    cocktail: {
      back_to_shop: "Terug naar Winkel",
      add_to_cart: "Toevoegen aan Winkelwagen",
      ingredients: "Ingrediënten",
      instructions: "Instructies",
      nutrition: "Voedings Informatie",
      alcohol_content: "Alcohol Gehalte",
      alcohol_strength: "Alcoholsterkte",
      volume: "Volume",
      calories: "Calorieën",
      sugar: "Suiker",
      related_cocktails: "Gerelateerde Cocktails",
      size_selection: "Selecteer Maat",
      available_sizes: "Beschikbare Maten",
      flavor_profile: "Smaakkarakter",
      non_alcoholic_available: "Alcoholvrije optie beschikbaar",
      non_alcoholic: "Alcoholvrij",
      alcohol: "alcohol",
      non_alcoholic_version_available: "Alcoholvrije versie beschikbaar",
      quantity: "Hoeveelheid",
      total_price: "Totale Prijs",
      no_sizes: "Geen maten beschikbaar.",
    },
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    // Cargar idioma guardado
    try {
      const savedLanguage = localStorage.getItem("cosmic-language") as Language;
      if (savedLanguage && ["es", "en", "nl"].includes(savedLanguage)) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      console.warn("Error loading language from localStorage:", error);
    } finally {
      setIsInitialized(true);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("cosmic-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    try {
      const keys = key.split(".");
      let value: any = translations[language];

      // Navegar por las claves anidadas
      for (const k of keys) {
        if (value && typeof value === "object" && k in value) {
          value = value[k];
        } else {
          console.warn(
            `Translation key not found: ${key} for language: ${language}`
          );
          return key; // Devolver la clave si no se encuentra
        }
      }

      // Si encontramos una cadena, procesar parámetros
      if (typeof value === "string") {
        if (params) {
          return value.replace(/\{(\w+)\}/g, (match, paramKey) => {
            return params[paramKey]?.toString() || match;
          });
        }
        return value;
      }

      console.warn(`Translation value is not a string for key: ${key}`);
      return key;
    } catch (error) {
      console.error(`Error translating key ${key}:`, error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, isInitialized }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    console.error("useLanguage must be used within a LanguageProvider");
    // Fallback para evitar crashes
    return {
      language: "es" as const,
      setLanguage: () => {},
      t: (key: string, params?: Record<string, string | number>) => key,
      isInitialized: false,
    };
  }
  return context;
}
