"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "es" | "en" | "nl";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isInitialized: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Traducciones
const translations = {
  es: {
    nav: {
      shop: "Tienda",
      events: "Eventos",
      about: "Sobre Nosotros",
      contact: "Contacto",
      cart: "Carrito",
      account: "Cuenta",
      home: "Inicio",
      menu: "Menú",
      navigation: "Navegación",
      actions: "Acciones",
      login: "Iniciar Sesión",
    },
    shop: {
      all_cocktails: "Todos los Cócteles",
      non_alcoholic: "Sin Alcohol",
      strong_drinks: "Bebidas Fuertes",
      light_fresh: "Ligero y Fresco",
      tropical: "Delicias Tropicales",
      tropical_description:
        "Prueba el verano en cada sorbo. Explora nuestros cócteles tropicales.",
      cosmic_classics: "Clásicos Cósmicos",
      cosmic_classics_description:
        "Recetas legendarias, ahora embotelladas para tus eventos.",
      non_alcoholic_description: "Cócteles que impresionan — sin alcohol.",
      from_price: "Desde €{price}",
      coming_soon: "Próximamente",
      add_to_cart: "Añadir al Carrito",
      choose_size: "Elige un tamaño",
      no_sizes_available: "No hay tamaños disponibles",
      view_details: "Ver Detalles",
      explore_now: "Explorar ahora",
    },
    sizes: {
      small_bottle: "Botella pequeña",
      shot: "Chupito",
      shots: "Chupitos",
    },
    cart: {
      title: "Carrito",
      empty_title: "Tu carrito está vacío",
      empty_subtitle: "¡Añade algunos cócteles deliciosos para empezar!",
      start_shopping: "Comenzar a Comprar",
      item_size: "Tamaño",
      item_quantity: "Cantidad",
      item_price: "Precio",
      item_total: "Total",
      remove_item: "Eliminar",
      update_quantity: "Actualizar",
      subtotal: "Subtotal",
      shipping: "Envío",
      tax: "IVA",
      total: "Total",
      checkout_button: "Proceder al Pago",
      continue_shopping: "Seguir Comprando",
      order_summary: "Resumen del Pedido",
      item_singular: "artículo",
      item_plural: "artículos",
      in_cart: "en tu carrito",
      free_shipping: "Gratis",
      clear_cart: "Vaciar Carrito",
      free_shipping_note: "Envío gratis en pedidos superiores a 50€",
      loading: "Cargando...",
      loading_cart: "Cargando carrito...",
      error_loading: "Error al cargar el carrito",
      retry: "Reintentar",
    },
    favorites: {
      title: "Mis Favoritos",
      subtitle: "Tus cocktails espaciales favoritos guardados para siempre",
      empty: "No tienes favoritos aún",
      explore: "Explorar Catálogo",
      added_on: "Añadido el {date}",
    },
    settings: {
      title: "Configuración",
      subtitle:
        "Personaliza tu experiencia espacial y gestiona tus preferencias",
      appearance: "Apariencia",
      theme: "Tema",
      light: "Claro",
      dark: "Oscuro",
      coming_soon: "Próximamente",
      language: "Idioma y Región",
      language_label: "Idioma",
      currency: "Moneda",
      currency_note: "Solo EUR disponible para envíos en Holanda.",
      notifications: {
        title: "Notificaciones",
        email: {
          title: "Notificaciones por email",
          description: "Recibe actualizaciones sobre tus pedidos",
        },
        push: {
          title: "Notificaciones push",
          description: "Recibe notificaciones en tu navegador",
        },
        marketing: {
          title: "Marketing",
          description: "Recibe ofertas y promociones especiales",
        },
      },
      privacy: {
        title: "Privacidad",
        profile_public: {
          title: "Perfil público",
          description: "Permite que otros usuarios vean tu perfil",
        },
        show_orders: {
          title: "Mostrar pedidos",
          description: "Permite que otros vean tus pedidos públicos",
        },
      },
      save_changes: "Guardar Cambios",
      unsaved_changes: "Tienes cambios sin guardar",
      saved: "Configuración guardada!",
      error: "Error: {error}",
    },
    footer: {
      explore: "Explorar",
      description:
        "Bebidas curadas y experiencias premium de cócteles, servidas con sabor estelar.",
      contact: "Contacto:",
      copyright: "© 2025 CosmoCocktails. Todos los derechos reservados.",
    },
    common: {
      loading: "Cargando...",
      error: "Error",
      retry: "Reintentar",
      save: "Guardar",
      cancel: "Cancelar",
      close: "Cerrar",
      back: "Volver",
      reload: "Recargar",
    },
    home: {
      hero_words: [
        "Cócteles",
        "de",
        "calidad",
        "de",
        "bar.",
        "Entregados",
        "a",
        "tu",
        "órbita.",
      ],
      hero_subtitle: "Creados por mixólogos. Servidos con sabor estelar.",
      experience_title: "Más que una bebida — es una experiencia",
      experience_description:
        "Creados con los mejores ingredientes, diseñados para quienes exigen más que solo una bebida — un momento inolvidable. Entregados con elegancia, saboreados con estilo.",
      quiz_button: "Toma nuestro Quiz de Cócteles",
      explore_button: "Explorar Ahora",
      how_it_works: "Cómo Funciona",
      step1_title: "Elige tu cóctel",
      step1_description:
        "Navega por nuestra selección curada de cócteles premium",
      step2_title: "Personaliza tu pedido",
      step2_description:
        "Selecciona el tamaño y personaliza según tus preferencias",
      step3_title: "Recibe en casa",
      step3_description:
        "Disfruta de cócteles de calidad de bar en la comodidad de tu hogar",
      featured_title: "Cócteles Destacados",
      featured_subtitle: "Nuestra selección más popular",
      cta_title: "¿Listo para tu viaje espacial?",
      cta_description: "Descubre el universo de sabores que te espera",
      cta_button: "Comenzar Ahora",
    },
    about: {
      title: "¿Qué es CosmoCocktails?",
      description:
        "CosmoCocktails nace de nuestra pasión por la mixología. Creamos cócteles de calidad de bar con ingredientes premium para que puedas disfrutarlos en cualquier lugar. Listos para servir, hermosamente empaquetados y siempre deliciosos.",
      how_help_title: "¿Cómo podemos ayudarte?",
      help1: "Cócteles premium entregados a tu puerta",
      help2: "Listos para beber — no necesitas habilidades de mixología",
      help3: "Recetas curadas para cada paladar",
      help4: "Perfectos para fiestas o relajarse en casa",
      mission_title: "Nuestra Misión",
      mission_description:
        "Llevar la experiencia de bar premium directamente a tu hogar, con cócteles que rivalizan con los mejores establecimientos del mundo.",
      values_title: "Nuestros Valores",
      quality: "Calidad",
      quality_desc: "Solo los mejores ingredientes y técnicas de mixología",
      innovation: "Innovación",
      innovation_desc: "Recetas únicas y presentaciones creativas",
      sustainability: "Sostenibilidad",
      sustainability_desc: "Embalaje ecológico y prácticas responsables",
      history_title: "Nuestra Historia y Valores",
      history_description:
        "Fundada en 2025, CosmoCocktails comenzó con una idea simple: llevar la sofisticación de un bar de cócteles a tu sala de estar. Nuestro equipo de mixólogos experimentados selecciona cuidadosamente cada ingrediente y cree en el servicio, la innovación y la sostenibilidad. Nuestro objetivo es elevar tus momentos con bebidas excepcionales mientras cuidamos nuestro planeta.",
      events_title: "Experiencias y Eventos",
      events_description:
        "Desde reuniones corporativas hasta celebraciones privadas, nuestro equipo crea experiencias de cócteles personalizadas — hacemos que tu evento sea memorable.",
      events_contact: "Para más información contáctanos",
      events_button: "Planifica tu evento",
      team_title: "Conoce al Equipo",
      team_founder: "Fundador y Mixólogo Principal",
      team_cofounder: "Co-fundador y Mixólogo Principal",
      team_developer: "Mixólogo y Desarrollador Web",
      feedback_title: "¿Tienes alguna sugerencia?",
      feedback_message:
        "Tu opinión es importante para nosotros. Ayúdanos a mejorar la experiencia cósmica.",
      contact_us: "Contáctanos",
    },
    contact: {
      title: "Contacto",
      subtitle:
        "¿Tienes alguna pregunta? Nos encantaría escucharte. Ponte en contacto con nosotros y te responderemos lo antes posible.",
      form_title: "Envíanos un Mensaje",
      form_description:
        "Completa el formulario y nos pondremos en contacto contigo lo antes posible.",
      form: {
        name: "Nombre",
        name_placeholder: "Tu nombre completo",
        name_help: "Introduce tu nombre completo",
        email: "Email",
        email_placeholder: "tu@email.com",
        phone: "Teléfono",
        phone_placeholder: "+34 123 456 789",
        phone_help: "Número de teléfono opcional",
        subject: "Asunto",
        subject_placeholder: "¿En qué podemos ayudarte?",
        subject_help: "Describe brevemente el motivo de tu consulta",
        message: "Mensaje",
        message_placeholder: "Escribe tu mensaje aquí...",
        message_help: "Proporciona todos los detalles necesarios",
        send: "Enviar Mensaje",
        sending: "Enviando...",
        clear: "Limpiar Formulario",
        additional_info: "Información Adicional",
        response_time: "Tiempo de respuesta: 24 horas",
        attention_hours: "Horario de atención: L-V 9:00-18:00",
        urgent_orders: "Para pedidos urgentes, contacta por teléfono",
        technical_support:
          "Soporte técnico disponible durante horario comercial",
      },
      info_title: "Información de Contacto",
      email: "Email",
      response_time: "Tiempo de respuesta: 24 horas",
      phone: "Teléfono",
      phone_hours: "Lunes a viernes, 9:00-18:00",
      address: "Dirección",
      hours: "Horarios",
      hours_weekdays: "Lunes - Viernes: 9:00 - 18:00",
      hours_saturday: "Sábado: 10:00 - 16:00",
      hours_sunday: "Domingo: Cerrado",
      faq_title: "Preguntas Frecuentes",
      faq_delivery: "¿Cuánto tiempo tarda la entrega?",
      faq_delivery_answer:
        "Las entregas estándar tardan entre 2-5 días laborables.",
      faq_cancel: "¿Puedo cancelar mi pedido?",
      faq_cancel_answer:
        "Puedes cancelar tu pedido hasta 24 horas después de realizarlo.",
      faq_international: "¿Hacen envíos internacionales?",
      faq_international_answer: "Actualmente solo enviamos dentro de España.",
      follow_us: "Síguenos",
    },
    events: {
      title: "Eventos",
      subtitle: "Únete a nuestras experiencias cósmicas",
      upcoming_title: "Próximos Eventos",
      past_title: "Eventos Anteriores",
      no_events: "No hay eventos programados",
      event_register: "Registrarse",
      event_details: "Ver Detalles",
      event_date: "Fecha",
      event_time: "Hora",
      event_location: "Ubicación",
      event_price: "Precio",
      event_description: "Descripción",
      card1_title: "Fiesta de Lanzamiento CosmoCocktails",
      card1_description:
        "Nuestro debut oficial en Róterdam con bebidas de autor y DJ en vivo.",
      card2_title: "Taller de Mixología Estelar",
      card2_description:
        "Masterclass práctica explorando los secretos de nuestras mezclas más populares.",
      card3_title: "Fiesta Galáctica de Año Nuevo",
      card3_description:
        "Despide el año entre las estrellas con cócteles cósmicos y sorpresas.",
    },
    checkout: {
      title: "Finalizar Compra",
      subtitle: "Completa tu pedido de forma segura",
      loading: "Cargando checkout...",
      error_loading: "Error al cargar checkout",
      empty_cart: "Tu carrito está vacío",
      start_shopping: "Comenzar a Comprar",
      contact_info: "Información de Contacto",
      full_name: "Nombre Completo",
      full_name_placeholder: "Tu nombre completo",
      email: "Email",
      email_placeholder: "tu@email.com",
      phone: "Teléfono",
      phone_placeholder: "+34 123 456 789",
      shipping_address: "Dirección de Envío",
      payment_info: "Información de Pago",
      preparing_payment: "Preparando pago seguro...",
      products_unavailable:
        "Algunos productos no están disponibles. Revisa tu carrito.",
      select_address: "Por favor, selecciona una dirección de envío.",
      order_summary: "Resumen del Pedido",
      subtotal: "Subtotal",
      items: "artículos",
      vat: "IVA",
      shipping: "Envío",
      free: "Gratis",
      total: "Total",
      free_shipping_note: "Envío gratuito en pedidos superiores a €50",
      inventory_validation: "Validación de Inventario",
      last_verification: "Última verificación",
      verify_inventory: "Verificar inventario",
      verifying_availability: "Verificando disponibilidad...",
      inventory_error: "Error al verificar inventario",
      all_products_available: "Todos los productos están disponibles",
      some_products_unavailable: "Algunos productos no están disponibles",
      requested: "Solicitado",
      units: "unidades",
      available: "Disponible",
      not_available: "No disponible",
      maximum: "Máximo",
      stock: "Stock",
      note: "Nota",
      inventory_note:
        "El inventario se verifica en tiempo real. Si un producto no está disponible, será eliminado automáticamente del carrito.",
      shipping_addresses: "Direcciones de Envío",
      home: "Casa",
      spain: "España",
      default: "Por defecto",
      add_new_address: "Agregar Nueva Dirección",
      edit_address: "Editar Dirección",
      new_address: "Nueva Dirección",
      address_name: "Nombre de la dirección",
      address_name_placeholder: "Casa, Oficina, etc.",
      address: "Dirección",
      address_placeholder: "Calle, número, piso, puerta",
      city: "Ciudad",
      city_placeholder: "Madrid",
      postal_code: "Código Postal",
      postal_code_placeholder: "28001",
      country: "País",
      country_placeholder: "España",
      set_as_default: "Establecer como dirección por defecto",
      update: "Actualizar",
      save: "Guardar",
      cancel: "Cancelar",
      unexpected_error: "Error inesperado",
      failed_create_order: "Error al crear el pedido",
      payment_protected:
        "Tu información de pago está protegida con encriptación de nivel bancario",
      processed_stripe: "Procesado de forma segura por Stripe",
      creating_order: "Creando pedido...",
      processing_payment: "Procesando pago...",
      complete_payment: "Completar Pago",
    },
    order: {
      success_title: "¡Pedido Realizado!",
      order_number: "Número de Pedido",
      copy: "Copiar",
      copied: "Copiado",
      status_ordered: "Ordenado",
      status_preparation: "Preparación",
      status_shipping: "En camino",
      status_completed: "Completado",
      current_status: "Estado Actual",
      need_help: "¿Necesitas ayuda?",
      ask_about_order: "Preguntar sobre el pedido",
      send_direct_message: "Envía un mensaje directo",
      call_phone: "Llamar por teléfono",
      send_message: "Enviar mensaje",
      message_placeholder: "Escribe tu pregunta sobre el pedido...",
      cancel: "Cancelar",
      message_sent: "Tu mensaje ha sido enviado. Te responderemos pronto.",
      status_messages: {
        ordered: "Tu pedido ha sido confirmado y está siendo procesado.",
        ordered_next: "Nuestro equipo comenzará a preparar tu pedido pronto.",
        preparing: "Tu pedido está siendo preparado con ingredientes frescos.",
        preparing_next: "Una vez listo, será enviado para entrega.",
        shipping: "Tu pedido está en camino hacia ti.",
        shipping_next: "Recibirás una notificación cuando llegue.",
        completed: "¡Tu pedido ha sido entregado exitosamente!",
        completed_next: "Esperamos que disfrutes tu experiencia espacial.",
        processing: "Procesando tu pedido...",
        processing_next: "Te mantendremos informado sobre el progreso.",
      },
      not_found: "Pedido no encontrado",
      not_found_description: "Verifica el enlace o vuelve al inicio.",
      go_home: "Ir al inicio",
      continue_shopping: "Seguir comprando",
      view_orders: "Ver mis pedidos",
      payment_confirmed: "Pago confirmado — pedido realizado con éxito",
      items: "Artículos",
      quantity: "Cantidad",
      product_subtotal: "Subtotal productos",
      vat: "IVA",
      shipping_costs: "Gastos de envío",
      total: "Total",
      shipping_info: "Envío",
    },
    cocktail: {
      back_to_shop: "Volver a la Tienda",
      add_to_cart: "Añadir al Carrito",
      ingredients: "Ingredientes",
      instructions: "Instrucciones",
      nutrition: "Información Nutricional",
      alcohol_content: "Contenido de Alcohol",
      alcohol_strength: "Intensidad de alcohol",
      volume: "Volumen",
      calories: "Calorías",
      sugar: "Azúcar",
      related_cocktails: "Cócteles Relacionados",
      size_selection: "Seleccionar Tamaño",
      available_sizes: "Tamaños Disponibles",
      flavor_profile: "Perfil de sabor",
      non_alcoholic_available: "Opción sin alcohol disponible",
      quantity: "Cantidad",
      total_price: "Precio Total",
      no_sizes: "No hay tamaños disponibles.",
      not_found: "Cóctel no encontrado.",
    },
    dashboard: {
      welcome: "¡Bienvenido de vuelta, {{name}}! 🚀",
      explorer: "Explorador",
      mission_continue: "Tu misión espacial de cocktails continúa...",
      total_orders: "Pedidos Totales",
      total_spent: "Total Gastado",
      favorites: "Favoritos",
      member_since: "Miembro desde",
      recent_orders: "Pedidos Recientes",
      cocktail: "cocktail",
      cocktails: "cocktails",
      no_orders: "Aún no tienes pedidos",
      explore_catalog: "¡Explora nuestro catálogo y haz tu primer pedido!",
      quick_actions: "Acciones Rápidas",
      view_catalog: "Ver Catálogo",
      view_favorites: "Mis Favoritos",
    },
    admin: {
      panel_title: "Admin Panel",
      authorized_only: "Solo personal autorizado",
      verified: "Verificado",
      refresh_permissions: "Refrescar permisos",
      redirecting: "Redirigiendo…",
      access: "Acceder",
    },
    account: {
      my_account: "Mi Cuenta",
      logout: "Cerrar Sesión",
      tabs: {
        dashboard: "Panel",
        profile: "Perfil",
        orders: "Pedidos",
        favorites: "Favoritos",
        settings: "Configuración",
        admin: "Panel de Administración",
      },
    },
    orders: {
      title: "Mis Pedidos",
      subtitle: "Gestiona y revisa todos tus pedidos espaciales",
      empty_title: "Aún no tienes pedidos",
      empty_subtitle:
        "¡Explora nuestro catálogo de cocktails espaciales y haz tu primer pedido!",
      view_details: "Ver Detalles",
      retry: "Reintentar",
      order_details: "Detalles del Pedido",
      order_total: "Total del Pedido:",
      order_number: "Pedido",
      items_total: "en total",
      error_loading: "Error al cargar pedidos",
      status: {
        paid: "Pagado",
        ordered: "Ordenado",
        preparing: "Preparación",
        on_the_way: "En camino",
        completed: "Completado",
        pending: "Pendiente",
        cancelled: "Cancelado",
        shipped: "Enviado",
      },
    },
    profile: {
      header_edit: "Editar",
      header_cancel: "Cancelar",
      personal_info: "Información Personal",
      full_name: "Nombre Completo",
      email_note: "El email no se puede cambiar por seguridad",
      phone: "Teléfono",
      account_info: "Información de la Cuenta",
      member_since: "Miembro desde",
      last_update: "Última actualización",
      unspecified: "No especificado",
      cancel: "Cancelar",
      save_changes: "Guardar Cambios",
      saving: "Guardando...",
    },
    auth: {
      login_title: "Iniciar Sesión",
      register_title: "Crear Cuenta",
      login_button: "Iniciar Sesión",
      register_button: "Crear Cuenta",
      login_error: "Error de inicio de sesión",
      login_success: "Sesión iniciada",
      login_success_message: "Has iniciado sesión correctamente.",
      register_error: "Error de registro",
      register_success: "Cuenta creada",
      register_success_message: "Revisa tu email para confirmar tu cuenta.",
      session_expired: "Sesión expirada",
      session_expired_message:
        "Tu sesión ha expirado. Por favor, inicia sesión nuevamente.",
      no_account: "¿No tienes cuenta? Crear una",
      have_account: "¿Ya tienes cuenta? Iniciar sesión",
      welcome_back: "¡Bienvenido de vuelta!",
      welcome_new: "¡Únete a la experiencia cósmica!",
      welcome_message: "Tu misión cósmica continúa...",
      join_community: "Únete a nuestra comunidad cósmica",
      email_placeholder: "tu@email.com",
      password_placeholder: "••••••••",
      full_name_placeholder: "Tu nombre completo",
      phone_placeholder: "+34 123 456 789",
      back_to_home: "Volver al inicio",
      join_message: "Descubre el universo de los cócteles de calidad",
      email: "Email",
      password: "Contraseña",
      confirm_password: "Confirmar Contraseña",
      full_name: "Nombre Completo",
      remember_me: "Recordarme",
      forgot_password: "¿Olvidaste tu contraseña?",
      loading: "Cargando...",
      invalid_credentials: "Credenciales inválidas",
      email_required: "El email es requerido",
      password_required: "La contraseña es requerida",
      password_min_length: "La contraseña debe tener al menos 6 caracteres",
      passwords_not_match: "Las contraseñas no coinciden",
      email_invalid: "Email inválido",
      name_required: "El nombre es requerido",
    },
  },
  en: {
    nav: {
      shop: "Shop",
      events: "Events",
      about: "About Us",
      contact: "Contact",
      cart: "Cart",
      account: "Account",
      home: "Home",
      menu: "Menu",
      navigation: "Navigation",
      actions: "Actions",
      login: "Login",
    },
    shop: {
      all_cocktails: "All Cocktails",
      non_alcoholic: "Non-Alcoholic",
      strong_drinks: "Strong Drinks",
      light_fresh: "Light & Fresh",
      tropical: "Tropical Delights",
      tropical_description:
        "Taste summer in every sip. Explore our tropical cocktails.",
      cosmic_classics: "Cosmic Classics",
      cosmic_classics_description:
        "Legendary recipes, now bottled for your events.",
      non_alcoholic_description:
        "Cocktails that impress — without the alcohol.",
      from_price: "From €{price}",
      coming_soon: "Coming Soon",
      add_to_cart: "Add to Cart",
      choose_size: "Choose a size",
      no_sizes_available: "No sizes available",
      view_details: "View Details",
      explore_now: "Explore now",
    },
    sizes: {
      small_bottle: "Small bottle",
      shot: "Shot",
      shots: "Shots",
    },
    cart: {
      title: "Cart",
      empty_title: "Your cart is empty",
      empty_subtitle: "Add some delicious cocktails to get started!",
      start_shopping: "Start Shopping",
      item_size: "Size",
      item_quantity: "Quantity",
      item_price: "Price",
      item_total: "Total",
      remove_item: "Remove",
      update_quantity: "Update",
      subtotal: "Subtotal",
      shipping: "Shipping",
      tax: "VAT",
      total: "Total",
      checkout_button: "Proceed to Checkout",
      continue_shopping: "Continue Shopping",
      order_summary: "Order Summary",
      item_singular: "item",
      item_plural: "items",
      in_cart: "in your cart",
      free_shipping: "Free",
      clear_cart: "Clear Cart",
      free_shipping_note: "Free shipping on orders over €50",
      loading: "Loading...",
      loading_cart: "Loading cart...",
      error_loading: "Error loading cart",
      retry: "Retry",
    },
    favorites: {
      title: "My Favorites",
      subtitle: "Your favorite space cocktails saved forever",
      empty: "You don't have favorites yet",
      explore: "Explore Catalog",
      added_on: "Added on {date}",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize your space experience and manage your preferences",
      appearance: "Appearance",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      coming_soon: "Coming Soon",
      language: "Language & Region",
      language_label: "Language",
      currency: "Currency",
      currency_note: "Only EUR available for shipping to Netherlands.",
      notifications: {
        title: "Notifications",
        email: {
          title: "Email notifications",
          description: "Receive updates about your orders",
        },
        push: {
          title: "Push notifications",
          description: "Receive notifications in your browser",
        },
        marketing: {
          title: "Marketing",
          description: "Receive special offers and promotions",
        },
      },
      privacy: {
        title: "Privacy",
        profile_public: {
          title: "Public profile",
          description: "Allow other users to see your profile",
        },
        show_orders: {
          title: "Show orders",
          description: "Allow others to see your public orders",
        },
      },
      save_changes: "Save Changes",
      unsaved_changes: "You have unsaved changes",
      saved: "Settings saved!",
      error: "Error: {error}",
    },
    footer: {
      explore: "Explore",
      description:
        "Curated drinks & premium cocktail experiences, served with stellar taste.",
      contact: "Contact:",
      copyright: "© 2025 CosmoCocktails. All rights reserved.",
    },
    common: {
      loading: "Loading...",
      error: "Error",
      retry: "Retry",
      save: "Save",
      cancel: "Cancel",
      close: "Close",
      back: "Back",
      reload: "Reload",
    },
    home: {
      hero_words: [
        "Bar-quality",
        "cocktails.",
        "Delivered",
        "to",
        "your",
        "orbit.",
      ],
      hero_subtitle: "Crafted by mixologists. Served with stellar taste.",
      experience_title: "More than a drink — it's an experience",
      experience_description:
        "Crafted with the finest ingredients, designed for those who demand more than just a drink — an unforgettable moment. Delivered with elegance, savored with style.",
      quiz_button: "Take our Cocktail Quiz",
      explore_button: "Explore Now",
      how_it_works: "How It Works",
      step1_title: "Choose your cocktail",
      step1_description: "Browse our curated selection of premium cocktails",
      step2_title: "Customize your order",
      step2_description:
        "Select size and customize according to your preferences",
      step3_title: "Receive at home",
      step3_description:
        "Enjoy bar-quality cocktails in the comfort of your home",
      featured_title: "Featured Cocktails",
      featured_subtitle: "Our most popular selection",
      cta_title: "Ready for your space journey?",
      cta_description: "Discover the universe of flavors waiting for you",
      cta_button: "Start Now",
    },
    about: {
      title: "What is CosmoCocktails?",
      description:
        "CosmoCocktails is born from our passion for mixology. We craft bar-quality cocktails with premium ingredients so you can enjoy them anywhere. Ready to serve, beautifully packaged and always delicious.",
      how_help_title: "How can we help you?",
      help1: "Premium cocktails delivered to your door",
      help2: "Ready to drink — no mixology skills needed",
      help3: "Curated recipes for every taste",
      help4: "Perfect for parties or relaxing at home",
      mission_title: "Our Mission",
      mission_description:
        "Bring the premium bar experience directly to your home, with cocktails that rival the world's best establishments.",
      values_title: "Our Values",
      quality: "Quality",
      quality_desc: "Only the best ingredients and mixology techniques",
      innovation: "Innovation",
      innovation_desc: "Unique recipes and creative presentations",
      sustainability: "Sustainability",
      sustainability_desc: "Eco-friendly packaging and responsible practices",
      history_title: "Our Story & Values",
      history_description:
        "Founded in 2025, CosmoCocktails started with a simple idea: to bring the sophistication of a cocktail bar to your living room. Our team of seasoned mixologists carefully selects every ingredient and believes in service, innovation and sustainability. We aim to elevate your moments with exceptional drinks while caring for our planet.",
      events_title: "Experiences & Events",
      events_description:
        "From corporate gatherings to private celebrations, our team creates tailored cocktail experiences — we make your event memorable.",
      events_contact: "For more information contact us",
      events_button: "Plan your event",
      team_title: "Meet the Team",
      team_founder: "Founder & Head Mixologist",
      team_cofounder: "Co-founder & Head Mixologist",
      team_developer: "Mixologist & Web Developer",
      feedback_title: "Have any suggestions?",
      feedback_message:
        "Your opinion matters to us. Help us improve the cosmic experience.",
      contact_us: "Contact Us",
    },
    events: {
      title: "Events",
      subtitle: "Join our cosmic experiences",
      upcoming_title: "Upcoming Events",
      past_title: "Past Events",
      no_events: "No events scheduled",
      event_register: "Register",
      event_details: "View Details",
      event_date: "Date",
      event_time: "Time",
      event_location: "Location",
      event_price: "Price",
      event_description: "Description",
      card1_title: "CosmoCocktails Launch Party",
      card1_description:
        "Our official debut in Rotterdam with signature drinks and live DJ.",
      card2_title: "Stellar Mixology Workshop",
      card2_description:
        "Hands-on masterclass exploring the secrets behind our most popular blends.",
      card3_title: "Galactic New Year's Bash",
      card3_description:
        "Ring in the new year among the stars with cosmic cocktails and surprises.",
    },
    contact: {
      title: "Contact",
      subtitle:
        "Have any questions? We'd love to hear from you. Get in touch with us and we'll respond as soon as possible.",
      form_title: "Send us a Message",
      form_description:
        "Fill out the form and we'll get back to you as soon as possible.",
      form: {
        name: "Name",
        name_placeholder: "Your full name",
        name_help: "Enter your full name",
        email: "Email",
        email_placeholder: "your@email.com",
        phone: "Phone",
        phone_placeholder: "+34 123 456 789",
        phone_help: "Optional phone number",
        subject: "Subject",
        subject_placeholder: "How can we help you?",
        subject_help: "Briefly describe the reason for your inquiry",
        message: "Message",
        message_placeholder: "Write your message here...",
        message_help: "Provide all necessary details",
        send: "Send Message",
        sending: "Sending...",
        clear: "Clear Form",
        additional_info: "Additional Information",
        response_time: "Response time: 24 hours",
        attention_hours: "Business hours: Mon-Fri 9:00-18:00",
        urgent_orders: "For urgent orders, contact by phone",
        technical_support: "Technical support available during business hours",
      },
      info_title: "Contact Information",
      email: "Email",
      response_time: "Response time: 24 hours",
      phone: "Phone",
      phone_hours: "Monday to Friday, 9:00-18:00",
      address: "Address",
      hours: "Hours",
      hours_weekdays: "Monday - Friday: 9:00 - 18:00",
      hours_saturday: "Saturday: 10:00 - 16:00",
      hours_sunday: "Sunday: Closed",
      faq_title: "Frequently Asked Questions",
      faq_delivery: "How long does delivery take?",
      faq_delivery_answer: "Standard deliveries take 2-5 business days.",
      faq_cancel: "Can I cancel my order?",
      faq_cancel_answer:
        "You can cancel your order up to 24 hours after placing it.",
      faq_international: "Do you ship internationally?",
      faq_international_answer: "We currently only ship within Spain.",
      follow_us: "Follow Us",
    },
    checkout: {
      title: "Checkout",
      subtitle: "Complete your order securely",
      loading: "Loading checkout...",
      error_loading: "Error loading checkout",
      empty_cart: "Your cart is empty",
      start_shopping: "Start Shopping",
      contact_info: "Contact Information",
      full_name: "Full Name",
      full_name_placeholder: "Your full name",
      email: "Email",
      email_placeholder: "your@email.com",
      phone: "Phone",
      phone_placeholder: "+34 123 456 789",
      shipping_address: "Shipping Address",
      payment_info: "Payment Information",
      preparing_payment: "Preparing secure payment...",
      products_unavailable: "Some products are not available. Check your cart.",
      select_address: "Please select a shipping address.",
      order_summary: "Order Summary",
      subtotal: "Subtotal",
      items: "items",
      vat: "VAT",
      shipping: "Shipping",
      free: "Free",
      total: "Total",
      free_shipping_note: "Free shipping on orders over €50",
      inventory_validation: "Inventory Validation",
      last_verification: "Last verification",
      verify_inventory: "Verify inventory",
      verifying_availability: "Verifying availability...",
      inventory_error: "Error verifying inventory",
      all_products_available: "All products are available",
      some_products_unavailable: "Some products are not available",
      requested: "Requested",
      units: "units",
      available: "Available",
      not_available: "Not available",
      maximum: "Maximum",
      stock: "Stock",
      note: "Note",
      inventory_note:
        "Inventory is verified in real time. If a product is not available, it will be automatically removed from the cart.",
      shipping_addresses: "Shipping Addresses",
      home: "Home",
      spain: "Spain",
      default: "Default",
      add_new_address: "Add New Address",
      edit_address: "Edit Address",
      new_address: "New Address",
      address_name: "Address Name",
      address_name_placeholder: "Home, Office, etc.",
      address: "Address",
      address_placeholder: "Street, number, floor, door",
      city: "City",
      city_placeholder: "Madrid",
      postal_code: "Postal Code",
      postal_code_placeholder: "28001",
      country: "Country",
      country_placeholder: "Spain",
      set_as_default: "Set as default address",
      update: "Update",
      save: "Save",
      cancel: "Cancel",
      unexpected_error: "Unexpected error",
      failed_create_order: "Failed to create order",
      payment_protected:
        "Your payment information is protected with bank-level encryption",
      processed_stripe: "Securely processed by Stripe",
      creating_order: "Creating order...",
      processing_payment: "Processing payment...",
      complete_payment: "Complete Payment",
      billing_title: "Billing Information",
      shipping_title: "Shipping Information",
      payment_title: "Payment Information",
      first_name: "First Name",
      last_name: "Last Name",
      card_number: "Card Number",
      expiry_date: "Expiry Date",
      cvv: "CVV",
      place_order: "Place Order",
      processing: "Processing...",
      success_title: "Order Placed!",
      success_message: "Your order has been processed successfully",
      order_number: "Order Number",
      estimated_delivery: "Estimated Delivery",
      not_found: "Order not found",
      not_found_description: "Check the link or return to home.",
      go_home: "Go Home",
      continue_shopping: "Continue Shopping",
      view_orders: "View My Orders",
      payment_confirmed: "Payment confirmed — order placed successfully",
      quantity: "Quantity",
      product_subtotal: "Product Subtotal",
      shipping_costs: "Shipping Costs",
      shipping_info: "Shipping",
      copy: "Copy",
      copied: "Copied",
      status_ordered: "Ordered",
      status_preparation: "Preparation",
      status_shipping: "On the way",
      status_completed: "Completed",
      current_status: "Current Status",
      need_help: "Need help?",
      ask_about_order: "Ask about the order",
      send_direct_message: "Send a direct message",
      call_phone: "Call by phone",
      send_message: "Send message",
      message_placeholder: "Write your question about the order...",
      message_sent: "Your message has been sent. We will respond soon.",
      status_messages: {
        ordered: "Your order has been confirmed and is being processed.",
        ordered_next: "Our team will start preparing your order soon.",
        preparing: "Your order is being prepared with fresh ingredients.",
        preparing_next: "Once ready, it will be sent for delivery.",
        shipping: "Your order is on its way to you.",
        shipping_next: "You will receive a notification when it arrives.",
        completed: "Your order has been delivered successfully!",
        completed_next: "We hope you enjoy your cosmic experience.",
        processing: "Processing your order...",
      },
    },
    order: {
      success_title: "Order Placed!",
      order_number: "Order Number",
      copy: "Copy",
      copied: "Copied",
      status_ordered: "Ordered",
      status_preparation: "Preparation",
      status_shipping: "On the way",
      status_completed: "Completed",
      current_status: "Current Status",
      need_help: "Need help?",
      ask_about_order: "Ask about the order",
      send_direct_message: "Send a direct message",
      call_phone: "Call by phone",
      send_message: "Send message",
      message_placeholder: "Write your question about the order...",
      message_sent: "Your message has been sent. We will respond soon.",
      status_messages: {
        ordered: "Your order has been confirmed and is being processed.",
        ordered_next: "Our team will start preparing your order soon.",
        preparing: "Your order is being prepared with fresh ingredients.",
        preparing_next: "Once ready, it will be sent for delivery.",
        shipping: "Your order is on its way to you.",
        shipping_next: "You will receive a notification when it arrives.",
        completed: "Your order has been delivered successfully!",
        completed_next: "We hope you enjoy your cosmic experience.",
        processing: "Processing your order...",
        processing_next: "We will keep you informed about the progress.",
      },
      not_found: "Order not found",
      not_found_description: "Check the link or return to home.",
      go_home: "Go Home",
      continue_shopping: "Continue Shopping",
      view_orders: "View My Orders",
      payment_confirmed: "Payment confirmed — order placed successfully",
      items: "Items",
      quantity: "Quantity",
      product_subtotal: "Product Subtotal",
      vat: "VAT",
      shipping_costs: "Shipping Costs",
      total: "Total",
      shipping_info: "Shipping",
    },
    cocktail: {
      back_to_shop: "Back to Shop",
      add_to_cart: "Add to Cart",
      ingredients: "Ingredients",
      instructions: "Instructions",
      nutrition: "Nutrition Information",
      alcohol_content: "Alcohol Content",
      alcohol_strength: "Alcohol strength",
      volume: "Volume",
      calories: "Calories",
      sugar: "Sugar",
      related_cocktails: "Related Cocktails",
      size_selection: "Select Size",
      available_sizes: "Available Sizes",
      flavor_profile: "Flavor profile",
      non_alcoholic_available: "Non-alcoholic option available",
      quantity: "Quantity",
      total_price: "Total Price",
      no_sizes: "No sizes available.",
      not_found: "Cocktail not found.",
    },
    dashboard: {
      welcome: "Welcome back, {{name}}! 🚀",
      explorer: "Explorer",
      mission_continue: "Your space cocktail mission continues...",
      total_orders: "Total Orders",
      total_spent: "Total Spent",
      favorites: "Favorites",
      member_since: "Member since",
      recent_orders: "Recent Orders",
      cocktail: "cocktail",
      cocktails: "cocktails",
      no_orders: "You don't have any orders yet",
      explore_catalog: "Explore our catalog and make your first order!",
      quick_actions: "Quick Actions",
      view_catalog: "View Catalog",
      view_favorites: "My Favorites",
      view_orders: "Order History",
    },
    admin: {
      panel_title: "Admin Panel",
      authorized_only: "Authorized personnel only",
      verified: "Verified",
      refresh_permissions: "Refresh permissions",
      redirecting: "Redirecting…",
      access: "Access",
    },
    account: {
      my_account: "My Account",
      logout: "Log Out",
      tabs: {
        dashboard: "Dashboard",
        profile: "Profile",
        orders: "Orders",
        favorites: "Favorites",
        settings: "Settings",
        admin: "Admin Panel",
      },
    },
    orders: {
      title: "My Orders",
      subtitle: "Manage and review all your cosmic orders",
      empty_title: "You don't have orders yet",
      empty_subtitle:
        "Explore our cosmic cocktail catalog and place your first order!",
      view_details: "View Details",
      retry: "Retry",
      order_details: "Order Details",
      order_total: "Order Total:",
      order_number: "Order",
      items_total: "in total",
      error_loading: "Error loading orders",
      status: {
        paid: "Paid",
        ordered: "Ordered",
        preparing: "Preparing",
        on_the_way: "On the way",
        completed: "Completed",
        pending: "Pending",
        cancelled: "Cancelled",
        shipped: "Shipped",
      },
    },
    profile: {
      header_edit: "Edit",
      header_cancel: "Cancel",
      personal_info: "Personal Information",
      full_name: "Full Name",
      email_note: "Email cannot be changed for security",
      phone: "Phone",
      account_info: "Account Information",
      member_since: "Member since",
      last_update: "Last update",
      unspecified: "Unspecified",
      cancel: "Cancel",
      save_changes: "Save Changes",
      saving: "Saving...",
    },
    auth: {
      login_title: "Sign In",
      register_title: "Create Account",
      login_button: "Sign In",
      register_button: "Create Account",
      login_error: "Sign in error",
      login_success: "Signed in",
      login_success_message: "You have successfully signed in.",
      register_error: "Registration error",
      register_success: "Account created",
      register_success_message: "Check your email to confirm your account.",
      session_expired: "Session expired",
      session_expired_message:
        "Your session has expired. Please sign in again.",
      no_account: "Don't have an account? Create one",
      have_account: "Already have an account? Sign in",
      welcome_back: "Welcome back!",
      welcome_new: "Join the cosmic experience!",
      welcome_message: "Your cosmic mission continues...",
      join_community: "Join our cosmic community",
      email_placeholder: "your@email.com",
      password_placeholder: "••••••••",
      full_name_placeholder: "Your full name",
      phone_placeholder: "+1 234 567 890",
      back_to_home: "Back to home",
      join_message: "Discover the universe of quality cocktails",
      email: "Email",
      password: "Password",
      confirm_password: "Confirm Password",
      full_name: "Full Name",
      remember_me: "Remember me",
      forgot_password: "Forgot your password?",
      loading: "Loading...",
      invalid_credentials: "Invalid credentials",
      email_required: "Email is required",
      password_required: "Password is required",
      password_min_length: "Password must be at least 6 characters",
      passwords_not_match: "Passwords do not match",
      email_invalid: "Invalid email",
      name_required: "Name is required",
    },
  },
  nl: {
    nav: {
      shop: "Winkel",
      events: "Evenementen",
      about: "Over Ons",
      contact: "Contact",
      cart: "Winkelwagen",
      account: "Account",
      home: "Home",
      menu: "Menu",
      navigation: "Navigatie",
      actions: "Acties",
      login: "Inloggen",
    },
    shop: {
      all_cocktails: "Alle Cocktails",
      non_alcoholic: "Alcoholvrij",
      strong_drinks: "Sterke Drankjes",
      light_fresh: "Licht & Vers",
      tropical: "Tropische Delicatessen",
      tropical_description:
        "Proef de zomer in elke slok. Verken onze tropische cocktails.",
      cosmic_classics: "Kosmische Klassiekers",
      cosmic_classics_description:
        "Legendarische recepten, nu gebotteld voor jouw evenementen.",
      non_alcoholic_description: "Cocktails die indruk maken — zonder alcohol.",
      from_price: "Vanaf €{price}",
      coming_soon: "Binnenkort",
      add_to_cart: "Toevoegen aan Winkelwagen",
      choose_size: "Kies een maat",
      no_sizes_available: "Geen maten beschikbaar",
      view_details: "Bekijk Details",
      explore_now: "Nu verkennen",
    },
    sizes: {
      small_bottle: "Kleine fles",
      shot: "Shot",
      shots: "Shots",
    },
    cart: {
      title: "Winkelwagen",
      empty_title: "Je winkelwagen is leeg",
      empty_subtitle: "Voeg wat heerlijke cocktails toe om te beginnen!",
      start_shopping: "Begin met Winkelen",
      item_size: "Maat",
      item_quantity: "Hoeveelheid",
      item_price: "Prijs",
      item_total: "Totaal",
      remove_item: "Verwijderen",
      update_quantity: "Bijwerken",
      subtotal: "Subtotaal",
      shipping: "Verzending",
      tax: "BTW",
      total: "Totaal",
      checkout_button: "Doorgaan naar Kassa",
      continue_shopping: "Verder Winkelen",
      order_summary: "Bestelling Overzicht",
      item_singular: "artikel",
      item_plural: "artikelen",
      in_cart: "in je winkelwagen",
      free_shipping: "Gratis",
      clear_cart: "Winkelwagen Leegmaken",
      free_shipping_note: "Gratis verzending bij bestellingen boven €50",
      loading: "Laden...",
      loading_cart: "Winkelwagen laden...",
      error_loading: "Fout bij laden winkelwagen",
      retry: "Opnieuw proberen",
    },
    favorites: {
      title: "Mijn Favorieten",
      subtitle: "Je favoriete ruimte cocktails voor altijd bewaard",
      empty: "Je hebt nog geen favorieten",
      explore: "Verken Catalogus",
      added_on: "Toegevoegd op {date}",
    },
    settings: {
      title: "Instellingen",
      subtitle: "Pas je ruimte-ervaring aan en beheer je voorkeuren",
      appearance: "Uiterlijk",
      theme: "Thema",
      light: "Licht",
      dark: "Donker",
      coming_soon: "Binnenkort",
      language: "Taal & Regio",
      language_label: "Taal",
      currency: "Valuta",
      currency_note: "Alleen EUR beschikbaar voor verzending naar Nederland.",
      notifications: {
        title: "Meldingen",
        email: {
          title: "E-mail meldingen",
          description: "Ontvang updates over je bestellingen",
        },
        push: {
          title: "Push meldingen",
          description: "Ontvang meldingen in je browser",
        },
        marketing: {
          title: "Marketing",
          description: "Ontvang speciale aanbiedingen en promoties",
        },
      },
      privacy: {
        title: "Privacy",
        profile_public: {
          title: "Openbaar profiel",
          description: "Sta andere gebruikers toe je profiel te bekijken",
        },
        show_orders: {
          title: "Toon bestellingen",
          description: "Sta anderen toe je openbare bestellingen te bekijken",
        },
      },
      save_changes: "Wijzigingen Opslaan",
      unsaved_changes: "Je hebt niet-opgeslagen wijzigingen",
      saved: "Instellingen opgeslagen!",
      error: "Fout: {error}",
    },
    footer: {
      explore: "Verken",
      description:
        "Gecureerde drankjes & premium cocktail ervaringen, geserveerd met sterren smaak.",
      contact: "Contact:",
      copyright: "© 2025 CosmoCocktails. Alle rechten voorbehouden.",
    },
    orders: {
      title: "Mijn Bestellingen",
      subtitle: "Beheer en bekijk al je kosmische bestellingen",
      empty_title: "Je hebt nog geen bestellingen",
      empty_subtitle:
        "Verken onze kosmische cocktailcatalogus en plaats je eerste bestelling!",
      view_details: "Bekijk Details",
      retry: "Opnieuw proberen",
      order_details: "Bestelling Details",
      order_total: "Totaal Bestelling:",
      order_number: "Bestelling",
      items_total: "in totaal",
      error_loading: "Fout bij laden bestellingen",
      status: {
        paid: "Betaald",
        ordered: "Besteld",
        preparing: "Voorbereiden",
        on_the_way: "Onderweg",
        completed: "Voltooid",
        pending: "In behandeling",
        cancelled: "Geannuleerd",
        shipped: "Verzonden",
      },
    },
    profile: {
      header_edit: "Bewerken",
      header_cancel: "Annuleren",
      personal_info: "Persoonlijke Informatie",
      full_name: "Volledige Naam",
      email_note: "E-mail kan om veiligheidsredenen niet worden gewijzigd",
      phone: "Telefoon",
      account_info: "Accountinformatie",
      member_since: "Lid sinds",
      last_update: "Laatste update",
      unspecified: "Niet gespecificeerd",
      cancel: "Annuleren",
      save_changes: "Wijzigingen Opslaan",
      saving: "Opslaan...",
    },
    auth: {
      login_title: "Inloggen",
      register_title: "Account Aanmaken",
      login_button: "Inloggen",
      register_button: "Account Aanmaken",
      login_error: "Inlogfout",
      login_success: "Ingelogd",
      login_success_message: "Je bent succesvol ingelogd.",
      register_error: "Registratiefout",
      register_success: "Account aangemaakt",
      register_success_message:
        "Controleer je e-mail om je account te bevestigen.",
      session_expired: "Sessie verlopen",
      session_expired_message: "Je sessie is verlopen. Log opnieuw in.",
      no_account: "Geen account? Maak er een aan",
      have_account: "Al een account? Log in",
      welcome_back: "Welkom terug!",
      welcome_new: "Word lid van de kosmische ervaring!",
      welcome_message: "Je kosmische missie gaat door...",
      join_community: "Word lid van onze kosmische gemeenschap",
      email_placeholder: "jouw@email.com",
      password_placeholder: "••••••••",
      full_name_placeholder: "Je volledige naam",
      phone_placeholder: "+31 123 456 789",
      back_to_home: "Terug naar home",
      join_message: "Ontdek het universum van kwaliteitscocktails",
      email: "Email",
      password: "Wachtwoord",
      confirm_password: "Wachtwoord Bevestigen",
      full_name: "Volledige Naam",
      remember_me: "Onthoud mij",
      forgot_password: "Wachtwoord vergeten?",
      loading: "Laden...",
      invalid_credentials: "Ongeldige inloggegevens",
      email_required: "Email is verplicht",
      password_required: "Wachtwoord is verplicht",
      password_min_length: "Wachtwoord moet minimaal 6 tekens zijn",
      passwords_not_match: "Wachtwoorden komen niet overeen",
      email_invalid: "Ongeldige email",
      name_required: "Naam is verplicht",
    },
    dashboard: {
      welcome: "Welkom terug, {{name}}! 🚀",
      explorer: "Verkenner",
      mission_continue: "Je ruimte cocktail missie gaat door...",
      total_orders: "Totale Bestellingen",
      total_spent: "Totaal Uitgegeven",
      favorites: "Favorieten",
      member_since: "Lid sinds",
      recent_orders: "Recente Bestellingen",
      cocktail: "cocktail",
      cocktails: "cocktails",
      no_orders: "Je hebt nog geen bestellingen",
      explore_catalog: "Verken onze catalogus en plaats je eerste bestelling!",
      quick_actions: "Snelle Acties",
      view_catalog: "Bekijk Catalogus",
      view_favorites: "Mijn Favorieten",
      view_orders: "Bestelgeschiedenis",
    },
    contact: {
      title: "Contact CosmoCocktails",
      subtitle:
        "We zijn hier om je te helpen met vragen over onze cocktails, bestellingen of andere vragen. Jouw tevredenheid is onze prioriteit.",
      info_title: "Contactinformatie",
      email: "E-mail",
      response_time: "Antwoord binnen 24-48 uur",
      phone: "Telefoon",
      phone_hours: "Maandag tot vrijdag, 9:00-18:00",
      address: "Adres",
      hours: "Openingstijden",
      hours_weekdays: "Maandag - Vrijdag: 9:00 - 18:00",
      hours_saturday: "Zaterdag: 10:00 - 14:00",
      hours_sunday: "Zondag: Gesloten",
      faq_title: "Veelgestelde vragen",
      faq_delivery: "Hoe lang duurt het voordat mijn bestelling arriveert?",
      faq_delivery_answer:
        "Tussen 24-48 uur in Madrid, 2-3 dagen in de rest van Spanje.",
      faq_cancel: "Kan ik mijn bestelling annuleren?",
      faq_cancel_answer: "Ja, tot 2 uur na het plaatsen van de bestelling.",
      faq_international: "Doen jullie internationale verzending?",
      faq_international_answer:
        "Momenteel verzenden we alleen naar het Iberisch schiereiland.",
      follow_us: "Volg ons",
      form_title: "Neem contact op",
      form_description:
        "Heb je vragen over onze cocktails? Heb je hulp nodig met je bestelling? We zijn hier om je te helpen. Stuur ons een bericht en we reageren zo snel mogelijk.",
      form: {
        name: "Volledige naam",
        name_placeholder: "Je volledige naam",
        name_help: "Hoe wil je dat we je noemen",
        email: "E-mail",
        email_placeholder: "jouw@email.com",
        phone: "Telefoon (optioneel)",
        phone_placeholder: "+34 123 456 789",
        phone_help: "Om je sneller te kunnen bereiken indien nodig",
        subject: "Onderwerp",
        subject_placeholder: "Hoe kunnen we je helpen?",
        subject_help: "Korte beschrijving van je vraag",
        message: "Bericht",
        message_placeholder: "Vertel ons meer details over je vraag...",
        message_help:
          "Minimaal 10 karakters. Wees specifiek om ons beter te kunnen helpen.",
        send: "Bericht verzenden",
        sending: "Verzenden...",
        clear: "Formulier wissen",
        additional_info: "Aanvullende informatie",
        response_time: "Reactietijd: 24-48 uur",
        attention_hours: "Openingstijden: Maandag tot vrijdag, 9:00-18:00",
        urgent_orders: "Voor urgente bestellingen, bel +34 123 456 789",
        technical_support:
          "Technische ondersteuning: soporte@cosmococktails.com",
      },
    },
    checkout: {
      title: "Afrekenen",
      subtitle: "Voltooi je bestelling veilig",
      loading: "Afrekenen laden...",
      error_loading: "Fout bij laden afrekenen",
      empty_cart: "Je winkelwagen is leeg",
      start_shopping: "Begin met Winkelen",
      contact_info: "Contactinformatie",
      full_name: "Volledige Naam",
      full_name_placeholder: "Je volledige naam",
      email: "E-mail",
      email_placeholder: "jouw@email.com",
      phone: "Telefoon",
      phone_placeholder: "+34 123 456 789",
      shipping_address: "Verzendadres",
      payment_info: "Betalingsinformatie",
      preparing_payment: "Veilige betaling voorbereiden...",
      products_unavailable:
        "Sommige producten zijn niet beschikbaar. Controleer je winkelwagen.",
      select_address: "Selecteer een verzendadres.",
      order_summary: "Bestellingsoverzicht",
      subtotal: "Subtotaal",
      items: "artikelen",
      vat: "BTW",
      shipping: "Verzending",
      free: "Gratis",
      total: "Totaal",
      free_shipping_note: "Gratis verzending bij bestellingen boven €50",
      inventory_validation: "Voorraadvalidatie",
      last_verification: "Laatste verificatie",
      verify_inventory: "Verificeer voorraad",
      verifying_availability: "Beschikbaarheid controleren...",
      inventory_error: "Fout bij verifiëren voorraad",
      all_products_available: "Alle producten zijn beschikbaar",
      some_products_unavailable: "Sommige producten zijn niet beschikbaar",
      requested: "Aangevraagd",
      units: "eenheden",
      available: "Beschikbaar",
      not_available: "Niet beschikbaar",
      maximum: "Maximum",
      stock: "Voorraad",
      note: "Opmerking",
      inventory_note:
        "De voorraad wordt in realtime geverifieerd. Als een product niet beschikbaar is, wordt het automatisch uit de winkelwagen verwijderd.",
      shipping_addresses: "Verzendadressen",
      home: "Thuis",
      spain: "Spanje",
      default: "Standaard",
      add_new_address: "Nieuw Adres Toevoegen",
      edit_address: "Adres Bewerken",
      new_address: "Nieuw Adres",
      address_name: "Adresnaam",
      address_name_placeholder: "Thuis, Kantoor, etc.",
      address: "Adres",
      address_placeholder: "Straat, nummer, verdieping, deur",
      city: "Stad",
      city_placeholder: "Madrid",
      postal_code: "Postcode",
      postal_code_placeholder: "28001",
      country: "Land",
      country_placeholder: "Spanje",
      set_as_default: "Instellen als standaardadres",
      update: "Bijwerken",
      save: "Opslaan",
      cancel: "Annuleren",
      unexpected_error: "Onverwachte fout",
      failed_create_order: "Fout bij het maken van de bestelling",
      payment_protected:
        "Uw betalingsinformatie is beschermd met bankniveau encryptie",
      processed_stripe: "Veilig verwerkt door Stripe",
      creating_order: "Bestelling maken...",
      processing_payment: "Betaling verwerken...",
      complete_payment: "Betaling Voltooien",
    },
    admin: {
      panel_title: "Admin Panel",
      authorized_only: "Alleen geautoriseerd personeel",
      verified: "Geverifieerd",
      refresh_permissions: "Machtigingen vernieuwen",
      redirecting: "Doorverwijzen…",
      access: "Toegang",
    },
    account: {
      my_account: "Mijn Account",
      logout: "Uitloggen",
      tabs: {
        dashboard: "Dashboard",
        profile: "Profiel",
        orders: "Bestellingen",
        favorites: "Favorieten",
        settings: "Instellingen",
        admin: "Beheerpaneel",
      },
    },
    common: {
      loading: "Laden...",
      error: "Fout",
      retry: "Opnieuw proberen",
      save: "Opslaan",
      cancel: "Annuleren",
      close: "Sluiten",
      back: "Terug",
      reload: "Herladen",
    },
    home: {
      hero_words: [
        "Bar-kwaliteit",
        "cocktails.",
        "Bezorgd",
        "op",
        "jouw",
        "baan.",
      ],
      hero_subtitle: "Gemaakt door mixologen. Geserveerd met sterren smaak.",
      experience_title: "Meer dan een drankje — het is een ervaring",
      experience_description:
        "Gemaakt met de beste ingrediënten, ontworpen voor degenen die meer eisen dan alleen een drankje — een onvergetelijk moment. Bezorgd met elegantie, gesavoureerd met stijl.",
      quiz_button: "Doe onze Cocktail Quiz",
      explore_button: "Verken Nu",
      how_it_works: "Hoe Het Werkt",
      step1_title: "Kies je cocktail",
      step1_description:
        "Blader door onze gecureerde selectie van premium cocktails",
      step2_title: "Personaliseer je bestelling",
      step2_description:
        "Selecteer maat en personaliseer volgens je voorkeuren",
      step3_title: "Ontvang thuis",
      step3_description:
        "Geniet van bar-kwaliteit cocktails in het comfort van je huis",
      featured_title: "Uitgelichte Cocktails",
      featured_subtitle: "Onze meest populaire selectie",
      cta_title: "Klaar voor je ruimtereis?",
      cta_description: "Ontdek het universum van smaken dat op je wacht",
      cta_button: "Begin Nu",
    },
    about: {
      title: "Wat is CosmoCocktails?",
      description:
        "CosmoCocktails is geboren uit onze passie voor mixologie. We maken bar-kwaliteit cocktails met premium ingrediënten zodat je ze overal kunt genieten. Klaar om te serveren, prachtig verpakt en altijd heerlijk.",
      how_help_title: "Hoe kunnen we je helpen?",
      help1: "Premium cocktails bezorgd aan je deur",
      help2: "Klaar om te drinken — geen mixologie vaardigheden nodig",
      help3: "Gecureerde recepten voor elke smaak",
      help4: "Perfect voor feesten of thuis ontspannen",
      mission_title: "Onze Missie",
      mission_description:
        "Breng de premium bar-ervaring direct naar je huis, met cocktails die wedijveren met de beste etablissementen ter wereld.",
      values_title: "Onze Waarden",
      quality: "Kwaliteit",
      quality_desc: "Alleen de beste ingrediënten en mixologie technieken",
      innovation: "Innovatie",
      innovation_desc: "Unieke recepten en creatieve presentaties",
      sustainability: "Duurzaamheid",
      sustainability_desc:
        "Milieuvriendelijke verpakking en verantwoorde praktijken",
      history_title: "Ons Verhaal & Waarden",
      history_description:
        "Opgericht in 2025, begon CosmoCocktails met een eenvoudig idee: de verfijning van een cocktailbar naar je woonkamer brengen. Ons team van ervaren mixologen selecteert zorgvuldig elk ingrediënt en gelooft in service, innovatie en duurzaamheid. We streven ernaar je momenten te verheffen met uitzonderlijke drankjes terwijl we voor onze planeet zorgen.",
      events_title: "Ervaringen & Evenementen",
      events_description:
        "Van bedrijfsbijeenkomsten tot privévieringen, ons team creëert op maat gemaakte cocktailervaringen — we maken je evenement onvergetelijk.",
      events_contact: "Voor meer informatie neem contact met ons op",
      events_button: "Plan je evenement",
      team_title: "Ontmoet het Team",
      team_founder: "Oprichter & Hoofd Mixoloog",
      team_cofounder: "Mede-oprichter & Hoofd Mixoloog",
      team_developer: "Mixoloog & Webontwikkelaar",
      feedback_title: "Heb je suggesties?",
      feedback_message:
        "Jouw mening is belangrijk voor ons. Help ons de kosmische ervaring te verbeteren.",
      contact_us: "Neem Contact Op",
    },
    events: {
      title: "Evenementen",
      subtitle: "Doe mee aan onze kosmische ervaringen",
      upcoming_title: "Aankomende Evenementen",
      past_title: "Vorige Evenementen",
      no_events: "Geen evenementen gepland",
      event_register: "Registreren",
      event_details: "Bekijk Details",
      event_date: "Datum",
      event_time: "Tijd",
      event_location: "Locatie",
      event_price: "Prijs",
      event_description: "Beschrijving",
      card1_title: "CosmoCocktails Lancering",
      card1_description:
        "Onze officiële debuut in Rotterdam met signature drankjes en live DJ.",
      card2_title: "Stellaire Mixologie Workshop",
      card2_description:
        "Hands-on masterclass met de geheimen achter onze populairste blends.",
      card3_title: "Galactisch Oud & Nieuw Feest",
      card3_description:
        "Vier het nieuwe jaar tussen de sterren met kosmische cocktails en verrassingen.",
    },
    cocktail: {
      back_to_shop: "Terug naar Winkel",
      add_to_cart: "Toevoegen aan Winkelwagen",
      ingredients: "Ingrediënten",
      instructions: "Instructies",
      nutrition: "Voedings Informatie",
      alcohol_content: "Alcohol Gehalte",
      alcohol_strength: "Alcoholsterkte",
      volume: "Volume",
      calories: "Calorieën",
      sugar: "Suiker",
      related_cocktails: "Gerelateerde Cocktails",
      size_selection: "Selecteer Maat",
      available_sizes: "Beschikbare Maten",
      flavor_profile: "Smaakkarakter",
      non_alcoholic_available: "Alcoholvrije optie beschikbaar",
      quantity: "Hoeveelheid",
      total_price: "Totale Prijs",
      no_sizes: "Geen maten beschikbaar.",
      not_found: "Cocktail niet gevonden.",
    },
    order: {
      success_title: "Bestelling succesvol geplaatst",
      order_number: "Bestelnummer",
      copy: "Kopiëren",
      status_ordered: "Besteld",
      status_preparation: "Voorbereiding",
      status_shipping: "Onderweg",
      status_completed: "Voltooid",
      continue_shopping: "Verder Winkelen",
      view_orders: "Bekijk Mijn Bestellingen",
      items: "Artikelen",
      quantity: "Hoeveelheid",
      product_subtotal: "Subtotaal producten",
      vat: "BTW",
      shipping_costs: "Verzendkosten",
      total: "Totaal",
      shipping_info: "Verzend Informatie",
      copied: "Gekopieerd",
      current_status: "Huidige Status",
      need_help: "Hulp nodig?",
      ask_about_order: "Vraag over de bestelling",
      send_direct_message: "Stuur een direct bericht",
      call_phone: "Bel per telefoon",
      send_message: "Bericht versturen",
      message_placeholder: "Schrijf je vraag over de bestelling...",
      cancel: "Annuleren",
      message_sent: "Je bericht is verzonden. We zullen snel reageren.",
      status_messages: {
        ordered: "Je bestelling is bevestigd en wordt verwerkt.",
        ordered_next:
          "Ons team zal binnenkort beginnen met het voorbereiden van je bestelling.",
        preparing: "Je bestelling wordt bereid met verse ingrediënten.",
        preparing_next: "Eenmaal klaar, wordt het verzonden voor levering.",
        shipping: "Je bestelling is onderweg naar je toe.",
        shipping_next: "Je ontvangt een melding wanneer het aankomt.",
        completed: "Je bestelling is succesvol afgeleverd!",
        completed_next: "We hopen dat je geniet van je kosmische ervaring.",
        processing: "Je bestelling wordt verwerkt...",
        processing_next: "We houden je op de hoogte van de voortgang.",
      },
    },
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    // Cargar idioma guardado
    try {
      const savedLanguage = localStorage.getItem("cosmic-language") as
        | Language
        | null;
      const legacyLanguage = localStorage.getItem("language") as
        | Language
        | null;
      const initialLanguage = savedLanguage || legacyLanguage;

      if (initialLanguage && ["es", "en", "nl"].includes(initialLanguage)) {
        setLanguageState(initialLanguage);
        if (!savedLanguage && legacyLanguage) {
          localStorage.setItem("cosmic-language", initialLanguage);
          localStorage.removeItem("language");
        }
      }
    } catch (error) {
      console.warn("Error loading language from localStorage:", error);
    } finally {
      setIsInitialized(true);
    }
  }, []);

  useEffect(() => {
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("cosmic-language", lang);
    localStorage.removeItem("language");
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    try {
      const keys = key.split(".");
      let value: any = translations[language];

      // Navegar por las claves anidadas
      for (const k of keys) {
        if (value && typeof value === "object" && k in value) {
          value = value[k];
        } else {
          console.warn(
            `Translation key not found: ${key} for language: ${language}`
          );
          return key; // Devolver la clave si no se encuentra
        }
      }

      // Si encontramos una cadena, procesar parámetros
      if (typeof value === "string") {
        if (params) {
          return value.replace(/\{(\w+)\}/g, (match, paramKey) => {
            return params[paramKey]?.toString() || match;
          });
        }
        return value;
      }

      console.warn(`Translation value is not a string for key: ${key}`);
      return key;
    } catch (error) {
      console.error(`Error translating key ${key}:`, error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, isInitialized }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    console.error("useLanguage must be used within a LanguageProvider");
    // Fallback para evitar crashes
    return {
      language: "es" as const,
      setLanguage: () => {},
      t: (key: string, params?: Record<string, string | number>) => key,
      isInitialized: false,
    };
  }
  return context;
}
